import { env } from '$env/dynamic/private';

const DEFAULT_PREFIX = 'ogcr3_';
export const ENTITY_PREFIX = env.OBP_ENTITY_PREFIX || DEFAULT_PREFIX;

export const ENTITY_PROJECT = `${ENTITY_PREFIX}project`;
export const ENTITY_PARCEL = `${ENTITY_PREFIX}parcel`;
export const ENTITY_PARCEL_OWNERSHIP_VERIFICATION = `${ENTITY_PREFIX}parcel_owner_verification`;
export const ENTITY_PROJECT_PARCEL_VERIFICATION = `${ENTITY_PREFIX}project_parcel_verification`;
export const ENTITY_PROJECT_VERIFICATION = `${ENTITY_PREFIX}project_verification`;
export const ENTITY_PARCEL_MONITORING_PERIOD_VERIFICATION = `${ENTITY_PREFIX}parcel_monitoring_period_verification`;
export const ENTITY_PROJECT_MONITORING_PERIOD_VERIFICATION = `${ENTITY_PREFIX}project_monitoring_period_verification`;

export const ENTITY_CONSTANTS = {
	ENTITY_PROJECT,
	ENTITY_PARCEL,
	ENTITY_PARCEL_OWNERSHIP_VERIFICATION,
	ENTITY_PROJECT_PARCEL_VERIFICATION,
	ENTITY_PROJECT_VERIFICATION,
	ENTITY_PARCEL_MONITORING_PERIOD_VERIFICATION,
	ENTITY_PROJECT_MONITORING_PERIOD_VERIFICATION
} as const;

export type EntityName = (typeof ENTITY_CONSTANTS)[keyof typeof ENTITY_CONSTANTS];
